id: AF8040486
title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
type: translation
pechas:
- IDF36D195
- I0AC9E711
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:13.135376
  last_modified_at: 2023-01-04 12:15:13.135385
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IDF36D195/FE2D: 276F
  I0AC9E711/3C2D: 276F
